package com.example.android.myanylist.models;

import android.graphics.Color;
import android.os.Parcel;
import android.os.Parcelable;
import android.util.Log;

import com.example.android.myanylist.R;

public class ContentItem implements Parcelable {
    private static final String TAG = "ContentItem";

    // vars
    private String title;                   // the title of the piece of media
    private int score;                      // the score out of ten (shown as half stars out of five)
    private String dateAdded;               // the date the piece of media was added to the database (autogenerated)
    private String dateCreated;             // the date the piece of media was created by its creator
    private int status;                     // the status of consumption (planning, watching, completed etc
    private String creator;                 // the name of the creator
    private String description;             // description of the piece of media
    private int image;                      // location of splash image depicting the piece of media;

    // standard constructor
    public ContentItem(String title, int score, String dateAdded, String dateCreated, int status, String creator, String description, int image) {
        this.title = title;
        this.score = score;
        this.dateAdded = dateAdded;        // should be autogenerated
        this.dateCreated = dateCreated;
        this.status = status;
        this.creator = creator;
        this.description = description;
        this.image = image;
    }

    // empty constructor
    public ContentItem(){
        this.title = "title";
        this.score = 0;
        this.dateAdded = "01012020";        // as above
        this.dateCreated = "01011970";
        this.status = 0;
        this.creator = "creator";
        this.description = "description";
        this.image = R.mipmap.ic_launcher;
    };

    protected ContentItem(Parcel in) {
        title = in.readString();
        score = in.readInt();
        dateAdded = in.readString();
        dateCreated = in.readString();
        status = in.readInt();
        creator = in.readString();
        description = in.readString();
        image = in.readInt();
    }

    public static final Creator<ContentItem> CREATOR = new Creator<ContentItem>() {
        @Override
        public ContentItem createFromParcel(Parcel in) {
            return new ContentItem(in);
        }

        @Override
        public ContentItem[] newArray(int size) {
            return new ContentItem[size];
        }
    };

    // tostring method
    @Override
    public String toString() {
        return "ContentItem{" +
                "title='" + title + '\'' +
                ", score=" + score +
                ", dateAdded='" + dateAdded + '\'' +
                ", dateCreated='" + dateCreated + '\'' +
                ", status='" + status + '\'' +
                ", creator='" + creator + '\'' +
                ", description='" + description + '\'' +
                ", image=" + image +
                '}';
    }

    // getter methods
    public String getTitle() {return title;}
    public int getScore() {return score;}
    public String getDateAdded() {return dateAdded;}
    public String getDateCreated() {return dateCreated;}
    public int getStatus() {return status;}
    public String getCreator() {return creator;}
    public String getDescription() {return description;}
    public int getImage() {return image;}

    // setter methods
    public void setTitle(String title) {this.title = title;}
    public void setScore(int score) {this.score = score;}
    public void setDateAdded(String dateAdded) {this.dateAdded = dateAdded;}            // should probably not exist
    public void setDateCreated(String dateCreated) {this.dateCreated = dateCreated;}
    public void setStatus(int status) {this.status = status;}
    public void setCreator(String creator) {this.creator = creator;}
    public void setDescription(String description) {this.description = description;}
    public void setImage(int image) {this.image = image;}

    // status types
    public final static int STATUS_PLANNING = 0;
    public final static int STATUS_IN_PROGRESS = 1;
    public final static int STATUS_COMPLETED = 2;
    public final static int STATUS_DROPPED = 3;

    public static String getStringStatus (int i) {
        switch (i) {
            case STATUS_PLANNING:
                return "Planning";
            case STATUS_IN_PROGRESS:
                return "In Progress";
            case STATUS_COMPLETED:
                return "Completed";
            case STATUS_DROPPED:
                return "Dropped";
            default:
                Log.e(TAG, "getStringStatus: invalid status");
                return "Invalid status";
        }
    }

    public static int getStatusColor (int i) {
        switch (i) {
            case STATUS_PLANNING:
                return R.color.status_planning_yellow;
            case STATUS_IN_PROGRESS:
                return R.color.status_in_progress_blue;
            case STATUS_COMPLETED:
                return R.color.status_completed_green;
            case STATUS_DROPPED:
                return R.color.status_dropped_red;
            default:
                Log.e(TAG, "getStatusColor: invalid status");
                return R.color.textGrey;
        }
    }

    //parcelable methods
    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(title);
        dest.writeInt(score);
        dest.writeString(dateAdded);
        dest.writeString(dateCreated);
        dest.writeInt(status);
        dest.writeString(creator);
        dest.writeString(description);
        dest.writeInt(image);
    }
}
